  /// Flutter icons NightTime
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NightTime
///      fonts:
///       - asset: fonts/NightTime.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NightTime {
  NightTime._();

  static const _kFontFam = 'NightTime';
  static const String? _kFontPkg = null;

  static const IconData nighttime_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
